server:
  port: 8082

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: 8235

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG  # Enable DEBUG level logging for security-related information

